/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

// 从环境变量读取 Supabase 配置
// 如果环境变量未设置，使用默认值（仅用于开发）
// 生产环境必须设置环境变量
export const projectId = import.meta.env.VITE_SUPABASE_PROJECT_ID || "lkuwbdnegatcpfikhsfn"
export const publicAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxrdXdiZG5lZ2F0Y3BmaWtoc2ZuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQ1ODI2ODgsImV4cCI6MjA4MDE1ODY4OH0.re665QwaxQsCOpFe4Fg6ymZJbkSB8A9AKsE2pH5IH_c"